//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Reply
    {
        public int ReplyId { get; set; }
        public string Reply1 { get; set; }
        public Nullable<int> ComID { get; set; }
        [JsonIgnore, XmlIgnore]
        public virtual Comment Comment { get; set; }
    }
}
